#!/usr/bin/env python3

# createcards
# Last Edited: 6/24/2026
# Author: John Wesley Thompson

from flashcard import FlashCard, FlashCardService, Word
from sentence_generator import OpenAISentenceGenerator, PROMPT_HEADER

from datetime import date
import sqlite3
import sys
from pathlib import Path


def main():

    argv = sys.argv
    if len(argv) != 2:
        print("usage: createcards 'filename.txt'")
        exit(1)
    else:
        filename = argv[1]

    vocab = readVocabFile(filename)
    print(vocab)

    # FlashCardService setup
    db_conn = sqlite3.connect("data/jmdict.db")
    db_conn.row_factory = sqlite3.Row
    generator = OpenAISentenceGenerator(model="gpt-4o-mini")
    fc_service = FlashCardService(db_conn, generator)

    flash_cards = fc_service.createFlashCards(vocab)

    db_conn.close()

    # create tsv file
    with open(f"tango_{date.today().strftime('%Y-%m-%d')}.tsv", "w") as outfile:
        for card in flash_cards:
            print(card.TSVString, file=outfile)

    print("\ntsv file created. Don't forget to add any missing values for\n"
          "definitions that were listed as issues. Possible reasons for\n"
          "issues:\n"
          "\n"
          "- Provided a spelling for a word but no reading\n"
          "    example: 猫 (not followed by a space and ねこ)\n"
          "- Provided a word that is not in the database or is misspelled\n"
    )


def readVocabFile(filename: str):

        path = Path(filename)
        if path.suffix != ".txt" and path.suffix != ".text":
            raise ValueError("Input file must be a text file.")

        try:
            with open(filename, "r", encoding='utf-8') as infile:
                lines = infile.readlines()

        except FileNotFoundError:
            raise FileNotFoundError(f"file '{filename}' not found.")

        for i, line in enumerate(lines):
            line = line.strip().split()

            if len(line) > 2:
                raise ValueError(f"line {line} is invalid input. Only 2 fields should be provided")

            elif len(line) == 1:
                line.insert(0, "")

            lines[i] = Word(line[0], line[1])

        return lines


main()
