#!/usr/bin/env python3

# createcards
# Last Edited: 6/19/2026
# Author John Wesley Thompson

import flashcard
from sentence_generator import OpenAISentenceGenerator
from sentence_generator import PROMPT_HEADER
from datetime import date
import sqlite3

import sys
# tts related includes 
from gtts import gTTS

from dictionary_entry import DictionaryEntry, Sense


def main():

    argv = sys.argv
    if len(argv) != 2:
        print("usage: createcards 'filename.txt'")
        exit(1)
    else:
        filename = argv[1]

    vocab = tuple(readWords(filename)) # vocab is a tuple of tuples (kanji, word), (..., ...)
    flashcards = [flashcard.FlashCard(word) for word in vocab if word]

    # generate sentences
    gpt_model = "gpt-4o-mini"
    generator = OpenAISentenceGenerator(model="gpt-4o-mini")

    print("---generating example sentences via chat gpt---")
    sentences = generator.generateSentences(PROMPT_HEADER, vocab)

    # gather definitions
    print("------searching database for definitions-------")
    db_conn = sqlite3.connect("data/jmdict.db")
    cursor = db_conn.cursor()

    entries = []
    for word in vocab:
        entries.append(findEntry(word, cursor))

    db_conn.close()

    # generate tts audio
    print("-------generating audio with google tts--------")
    word_filepaths, sentence_filepaths = generateTTSMp3(vocab, sentences)

    # add data to the flashcards
    for i in range(len(flashcards)):
        flashcards[i].sentences = sentences[i]
        flashcards[i].definition = entries[i].senses[0].glosses
        flashcards[i].word_audio_filepath = word_filepaths[i]
        flashcards[i].sentence_audio_filepath = sentence_filepaths[i]

    # create tsv file
    with open(f"tango_{date.today().strftime('%Y-%m-%d')}.tsv", "w") as outfile:
        for card in flashcards:
            print(card.TSVString, file=outfile)

    print("\ntsv file created. Don't forget to add any missing values for\n"
          "definitions that were listed as issues.\n")


def findEntry(word, cursor):
    my_entry = DictionaryEntry()

    # find word and assign entry_id
    if not word[0]:
        cursor.execute(
            """
                SELECT readings.entry_id 
                FROM readings
                WHERE readings.reading = ?
            """,
            (word[1],)
        )

    else: 
        cursor.execute(
            """
            SELECT spellings.entry_id 
            FROM spellings 
            JOIN readings 
            ON spellings.entry_id = readings.entry_id 
            WHERE spellings.spelling = ? AND readings.reading = ?
            """,
            (word[0], word[1])
        )
    my_entry.entry_id = cursor.fetchone()[0]

    # assign spellings
    cursor.execute(
        "SELECT spelling FROM spellings WHERE entry_id = ?",
        (my_entry.entry_id,)
    )
    my_entry.spellings = [x[0] for x in cursor.fetchall()]

    # assign readings
    cursor.execute(
        "SELECT reading FROM readings WHERE entry_id = ?",
        (my_entry.entry_id,)
    )
    my_entry.readings = [x[0] for x in cursor.fetchall()]

    # find sense ids
    cursor.execute(
        """
        SELECT sense_id 
        FROM senses 
        WHERE senses.entry_id = ?
        """,
        (my_entry.entry_id,)
    )
    sense_ids = [x[0] for x in cursor.fetchall()]

    # assign sense ids and find and assign glosses to sense objects
    for id in sense_ids:
        cursor.execute(
            """
            SELECT gloss 
            FROM glosses 
            WHERE glosses.sense_id = ?
            """,
            (id,)
        )
        my_entry.senses.append(Sense(id, ', '.join([x[0] for x in cursor.fetchall()])))

    print(my_entry.entry_id)
    print(my_entry.spellings)
    print(my_entry.readings)
    for sense in my_entry.senses:
        print(sense.glosses)

    return my_entry


def generateTTSMp3(vocab, sentences):
    reset_line = "\u001b[2K\r"

    word_filenames = []
    sentence_filenames = []
    for word, sentence in zip(vocab, sentences):
        print(f"{reset_line}Generating tts for {word[0] if word[0] else word[1]}", end="")

        nonempty_word = word[0] if word[0] else word[1]

        word_out_filename = f"{nonempty_word}.mp3"
        sentence_out_filename = f"{nonempty_word}_sentences.mp3"

        gtts_obj = gTTS(text=nonempty_word, lang='ja', slow=False)
        gtts_obj.save(word_out_filename)

        sentence = sentence.split("(")[0]
        gtts_obj = gTTS(text=sentence, lang='ja', slow=False)
        gtts_obj.save(sentence_out_filename)

        word_filenames.append(word_out_filename)
        sentence_filenames.append(sentence_out_filename)

    print() # newline for when the "generating tts" prints are complete

    return word_filenames, sentence_filenames


def readWords(filename: str):
        if filename.split('.')[1] != "txt" and filename.split('.')[1] != "text":
            print("file must be a text file")
            exit(1)

        try:
            infile = open(filename, "r", encoding='utf-8')
            words = infile.readlines()
            infile.close()
        except FileNotFoundError:
            print(f"file '{filename}' not found.")
            exit(1)

        return ([tuple(word.split()) if len(word.split()) == 2 else 
                 ("", word.strip()) for word in words])


main()
